apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: {{ .Values.image }}
        name: vote
        ports:
        - containerPort: 8080
          name: vote
        env:
        - name: FUNCTION_URL
          value: {{ .Values.function.url }}
