AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  MongoDBUsername:
    Type: String
  MongoDBPassword:
    Type: String
  MongoDBDatabase:
    Type: String
  MongoDBHost:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          "/event":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StoreToMongoAtlas.Arn}/invocations
              responses: {}

  StoreToMongoAtlas:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          MONGODB_USERNAME: !Ref MongoDBUsername
          MONGODB_PASSWORD: !Ref MongoDBPassword
          MONGODB_DATABASE: !Ref MongoDBDatabase
          MONGODB_HOST: !Ref MongoDBHost
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/event'
            Method: post
            RestApiId:
                Ref: ApiGateway
Outputs:
  ProdDataEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Dev/event"